version: '3'

services:
  housemap-db:
    image: mongo:latest
    restart: always
    container_name: houseMapDb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 13450:27017

    volumes:
      - /home/mongo:/data/db

  housemap-backend:
    build: ./backend/
    container_name: houseMapBackend

    ports:
      - 80:80

    volumes:
    - /home/data:/data
