version: '3'

services:
  housemap-db:
    image: mongo:latest
    restart: always
    container_name: housemap-db
    command: mongod --quiet --logpath /dev/null 
    environment:
      MONGO_INITDB_ROOT_USERNAME: Ybu7yNneQNKY7fXnc5nL262z1dE
      MONGO_INITDB_ROOT_PASSWORD: f4-NO_WtpyZOFejOu8_xwWRiZo0
    ports:
      - 27017:27017

    volumes:
      - /home/mongo:/data/db

  housemap-backend:
    build: ./backend/
    container_name: housemap-backend
    ports:
      - 8000:8000

    volumes:
    - /home/data:/data

    depends_on:
      - housemap-db
