version: '3'

services:
  housemap-db:
    image: mongo:latest
    restart: always
    container_name: houseMapDb
    environment:
      MONGO_INITDB_ROOT_USERNAME: Ybu7yNneQNKY7fXnc5nL262z1dE
      MONGO_INITDB_ROOT_PASSWORD: f4-NO_WtpyZOFejOu8_xwWRiZo0
    ports:
      - 13450:27017

    volumes:
      - /home/mongo:/data/db

  housemap-backend:
    build: ./backend/
    container_name: houseMapBackend

    ports:
      - 80:80

    volumes:
    - /home/data:/data
